#!/usr/bin/env sh
# This file is part of raphaelcohn swaddle. It is subject to the licence terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/swaddle/master/COPYRIGHT. No part of raphaelcohn swaddle, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
# Copyright © 2014-2015 The developers of raphaelcohn swaddle. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/raphaelcohn/swaddle/master/COPYRIGHT.


_program()
{
	core_usesIn core temporaryFiles variable/array
	core_usesIn swaddle
	
	swaddle()
	{
		swaddle_all
	}
}

_program_name='swaddle'
_program_version='unversioned'
_program_package_or_build=''
_program_copyright='(c) 2014 Raphael Cohn'
_program_licence='MIT'
_program_written_by='Raphael Cohn'
_program_path="$([ "${_program_fattening_program_path+set}" = 'set' ] && printf '%s\n' "$_program_fattening_program_path" || ([ "${0%/*}" = "${0}" ] && printf '%s\n' '.' || printf '%s\n' "${0%/*}"))"
_program_libPath="${_program_path}/lib"
_program_etcPath="${_program_path}/etc"
_program_varPath="${_program_path}/var"
_program_entrypoint='swaddle'

_program_commandLine_parseInitialise()
{
	:
}

_program_commandLine_helpMessage()
{
	_program_commandLine_helpMessage_usage="[OPTION]... -- [SWADDLE]..."
	_program_commandLine_helpMessage_description="Builds packages by 'swaddling' them."
	_program_commandLine_helpMessage_options="
  -s, --swaddling-path PATH   Path to swaddling (package definitions).
                              Defaults to current working directory:-
                              $(pwd)
  -o, --output-path PATH      Path to use when creating packages.
                              Created if it doesn't exist.
                              Defaults to current working directory:-
                              $(pwd)
  -t, --temporary-path PATH   Path to use when creating packages.
                              Override if using very large packages,
                              as we use rsync to reduce cumulative builds.
                              Created if it doesn't exist.
                              Defaults to:-
                              ${TMPDIR}
  -c, --clean-output [OFF]    Clean output on start. Defaults to OFF
  -p, --publish-github [OFF]  Publish to GitHub pages.
                              Defaults to OFF."
    _program_commandLine_helpMessage_optionsSpacing='     '
	_program_commandLine_helpMessage_configurationKeys="
  swaddle_swaddlingPath   Equivalent to --swaddling-path
  swaddle_outputPath     Equivalent to --output-path
  swaddle_temporaryPath  Equivalent to --temporary-path
"
	_program_commandLine_helpMessage_examples="
  ${_program_name} -s /some/path -- some-package
"
}

_program_commandLine_optionExists()
{
	case "$optionName" in
		
		s|swaddling-path)
			echo 'yes-argumented'
		;;
		
		o|output-path)
			echo 'yes-argumented'
		;;
		
		t|temporary-path)
			echo 'yes-argumented'
		;;
		
		c|clean-output)
			echo 'yes-optionally-argumented'
		;;
		
		p|publish-github)
			echo 'yes-optionally-argumented'
		;;
		
	esac
}

_program_commandLine_processOptionWithArgument()
{
	case "$optionName" in
		
		s|swaddling-path)
			core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			swaddle_swaddlingPath="$optionValue"
		;;
		
		o|output-path)
			core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			swaddle_outputPath="$optionValue"
		;;
		
		t|temporary-path)
			core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			swaddle_temporaryPath="$optionValue"
		;;
		
		c|clean-output)
			core_validate_isBoolean $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			swaddle_cleanOutput="$optionValue"
		;;
		
		p|publish-github)
			core_validate_isBoolean $core_commandLine_exitCode_USAGE 'option' "$optionNameIncludingHyphens" "$optionValue"
			swaddle_publishGithub="$optionValue"
		;;
		
	esac
}

_program_commandLine_processOptionWithoutArgument()
{
	case "$optionName" in
		
		c|clean-output)
			swaddle_cleanOutput=on
		;;
		
		p|publish-github)
			swaddle_publishGithub=on
		;;
		
	esac
}

_program_commandLine_handleNonOptions()
{
	core_variable_array_initialise swaddle_swaddling
	
	local swaddle
	for swaddle in "$@"
	do
		core_variable_array_append swaddle_swaddling "$swaddle"
	done
}

_program_commandLine_validate()
{
	if core_variable_isSet swaddle_swaddlingPath; then
		core_validate_folderPathReadableAndSearchable $core_commandLine_exitCode_CONFIG 'configuration setting' 'swaddle_swaddlingPath' "$swaddle_swaddlingPath"
	else
		core_message INFO "Defaulting --swaddling-path to current working directory"
		swaddle_swaddlingPath="$(pwd)"
	fi
	
	if core_variable_isSet swaddle_outputPath; then
		core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_CONFIG 'configuration setting' 'swaddle_outputPath' "$swaddle_outputPath"
	else
		core_message INFO "Defaulting --output-path to current working directory"
		swaddle_outputPath="$(pwd)"
	fi
	
	if core_variable_isSet swaddle_temporaryPath; then
		core_validate_folderPathIsReadableAndSearchableAndWritableOrCanBeCreated $core_commandLine_exitCode_CONFIG 'configuration setting' 'swaddle_temporaryPath' "$swaddle_temporaryPath"
	fi
	
	if core_variable_isSet swaddle_cleanOutput; then
		core_validate_isBoolean $core_commandLine_exitCode_CONFIG 'configuration setting' 'swaddle_cleanOutput' "$swaddle_cleanOutput"
	else
		swaddle_cleanOutput=off
	fi
	
	if core_variable_isSet swaddle_publishGithub; then
		core_validate_isBoolean $core_commandLine_exitCode_CONFIG 'configuration setting' 'swaddle_publishGithub' "$swaddle_publishGithub"
	else
		swaddle_publishGithub=off
	fi
	
	local potentialSwaddle
	if core_variable_array_isEmpty swaddle_swaddling; then
		pushd "$swaddle_swaddlingPath"
			
			set +f
			for potentialSwaddle in *
			do
				set +f
				if [ "$potentialSwaddle" = 'swaddling.conf.d' ]; then
					continue
				fi
				if core_path_isReadableAndSearchableFolderPath "$potentialSwaddle"; then
					core_variable_array_append swaddle_swaddling "$potentialSwaddle"
				fi
			done
			set -f
			
		popd
		if core_variable_array_isEmpty swaddle_swaddling; then
			core_message WARN "There are no swaddling in '$swaddle_swaddlingPath'"
		fi
	else
		_program_commandLine_validate_swaddling()
		{
			potentialSwaddle="$core_variable_array_element"
			if ! core_path_isReadableAndSearchableFolderPath "$swaddle_swaddlingPath"/"$potentialSwaddle"; then
				core_exitError $core_commandLine_exitCode_USAGE "The swaddle '$potentialSwaddle' is not a readable, searchable folder in the swaddle path '$swaddle_swaddlingPath'"
			fi
		}
		core_variable_array_iterate swaddle_swaddling _program_commandLine_validate_swaddling
	fi
}

# Assumes pwd, and so requires this code to be running from this folder
. "$_program_libPath"/shellfire/core/init.functions "$@"
